// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'4b83a98159a07f649387becac283bf973fcb69271dbe257f490b40e50ccb7b4a'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type AcademicScoreOutput = {
  readonly type: CodecTypes['mongo/string@1']['output'];
  readonly label: CodecTypes['mongo/string@1']['output'];
  readonly value: CodecTypes['mongo/double@1']['output'];
  readonly scale: CodecTypes['mongo/double@1']['output'];
};
export type AcademicScoreInput = {
  readonly type: CodecTypes['mongo/string@1']['input'];
  readonly label: CodecTypes['mongo/string@1']['input'];
  readonly value: CodecTypes['mongo/double@1']['input'];
  readonly scale: CodecTypes['mongo/double@1']['input'];
};
export type PortfolioRatingOutput = {
  readonly id: CodecTypes['mongo/string@1']['output'];
  readonly rating: CodecTypes['mongo/int32@1']['output'];
  readonly comment: CodecTypes['mongo/string@1']['output'] | null;
  readonly createdAt: CodecTypes['mongo/date@1']['output'];
};
export type PortfolioRatingInput = {
  readonly id: CodecTypes['mongo/string@1']['input'];
  readonly rating: CodecTypes['mongo/int32@1']['input'];
  readonly comment: CodecTypes['mongo/string@1']['input'] | null;
  readonly createdAt: CodecTypes['mongo/date@1']['input'];
};
export type PortfolioGalleryOutput = {
  readonly id: CodecTypes['mongo/string@1']['output'];
  readonly imageUrl: CodecTypes['mongo/string@1']['output'];
  readonly description: CodecTypes['mongo/string@1']['output'] | null;
  readonly createdAt: CodecTypes['mongo/date@1']['output'];
};
export type PortfolioGalleryInput = {
  readonly id: CodecTypes['mongo/string@1']['input'];
  readonly imageUrl: CodecTypes['mongo/string@1']['input'];
  readonly description: CodecTypes['mongo/string@1']['input'] | null;
  readonly createdAt: CodecTypes['mongo/date@1']['input'];
};
export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly Award: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly event: CodecTypes['mongo/string@1']['output'];
      readonly award: CodecTypes['mongo/string@1']['output'];
      readonly icon: CodecTypes['mongo/string@1']['output'] | null;
      readonly year: CodecTypes['mongo/int32@1']['output'];
      readonly rank: CodecTypes['mongo/int32@1']['output'] | null;
      readonly date: CodecTypes['mongo/date@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Career: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly position: CodecTypes['mongo/string@1']['output'];
      readonly company: CodecTypes['mongo/string@1']['output'];
      readonly location: CodecTypes['mongo/string@1']['output'];
      readonly startDate: CodecTypes['mongo/date@1']['output'];
      readonly endDate: CodecTypes['mongo/date@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly CoffeePlace: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly address: CodecTypes['mongo/string@1']['output'];
      readonly description: CodecTypes['mongo/string@1']['output'] | null;
      readonly mapCoordinate: CodecTypes['mongo/string@1']['output'] | null;
      readonly mapUrl: CodecTypes['mongo/string@1']['output'] | null;
      readonly image: CodecTypes['mongo/string@1']['output'] | null;
      readonly wifiProvider: CodecTypes['mongo/string@1']['output'] | null;
      readonly wifiSpeed: 'WEAK' | 'MEDIUM' | 'STRONG';
      readonly price: 'CHEAP' | 'MEDIUM' | 'EXPENSIVE';
      readonly parkFee: CodecTypes['mongo/int32@1']['output'] | null;
      readonly close: CodecTypes['mongo/string@1']['output'] | null;
      readonly open: CodecTypes['mongo/string@1']['output'] | null;
      readonly region: CodecTypes['mongo/string@1']['output'] | null;
      readonly recomended: CodecTypes['mongo/bool@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Education: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly logo: CodecTypes['mongo/string@1']['output'] | null;
      readonly web: CodecTypes['mongo/string@1']['output'] | null;
      readonly level: CodecTypes['mongo/string@1']['output'];
      readonly grade: CodecTypes['mongo/string@1']['output'] | null;
      readonly department: CodecTypes['mongo/string@1']['output'] | null;
      readonly studyProgram: CodecTypes['mongo/string@1']['output'] | null;
      readonly start: CodecTypes['mongo/date@1']['output'];
      readonly end: CodecTypes['mongo/date@1']['output'] | null;
      readonly place: CodecTypes['mongo/string@1']['output'];
      readonly academicScore: AcademicScoreOutput | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Organization: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly orgName: CodecTypes['mongo/string@1']['output'];
      readonly desc: CodecTypes['mongo/string@1']['output'] | null;
      readonly period: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly Portfolio: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly slug: CodecTypes['mongo/string@1']['output'];
      readonly image: CodecTypes['mongo/string@1']['output'];
      readonly techstack: ReadonlyArray<CodecTypes['mongo/string@1']['output']>;
      readonly shortDesc: CodecTypes['mongo/string@1']['output'] | null;
      readonly desc: CodecTypes['mongo/string@1']['output'] | null;
      readonly demoLink: CodecTypes['mongo/string@1']['output'] | null;
      readonly sourceCode: CodecTypes['mongo/string@1']['output'] | null;
      readonly private: CodecTypes['mongo/bool@1']['output'];
      readonly categoryIds: ReadonlyArray<CodecTypes['mongo/objectId@1']['output']>;
      readonly careerIds: ReadonlyArray<CodecTypes['mongo/objectId@1']['output']>;
      readonly ratings: ReadonlyArray<PortfolioRatingOutput>;
      readonly galleries: ReadonlyArray<PortfolioGalleryOutput>;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly PortfolioCategory: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly color: CodecTypes['mongo/string@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly password: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly Award: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly event: CodecTypes['mongo/string@1']['input'];
      readonly award: CodecTypes['mongo/string@1']['input'];
      readonly icon: CodecTypes['mongo/string@1']['input'] | null;
      readonly year: CodecTypes['mongo/int32@1']['input'];
      readonly rank: CodecTypes['mongo/int32@1']['input'] | null;
      readonly date: CodecTypes['mongo/date@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Career: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly position: CodecTypes['mongo/string@1']['input'];
      readonly company: CodecTypes['mongo/string@1']['input'];
      readonly location: CodecTypes['mongo/string@1']['input'];
      readonly startDate: CodecTypes['mongo/date@1']['input'];
      readonly endDate: CodecTypes['mongo/date@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly CoffeePlace: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly address: CodecTypes['mongo/string@1']['input'];
      readonly description: CodecTypes['mongo/string@1']['input'] | null;
      readonly mapCoordinate: CodecTypes['mongo/string@1']['input'] | null;
      readonly mapUrl: CodecTypes['mongo/string@1']['input'] | null;
      readonly image: CodecTypes['mongo/string@1']['input'] | null;
      readonly wifiProvider: CodecTypes['mongo/string@1']['input'] | null;
      readonly wifiSpeed: 'WEAK' | 'MEDIUM' | 'STRONG';
      readonly price: 'CHEAP' | 'MEDIUM' | 'EXPENSIVE';
      readonly parkFee: CodecTypes['mongo/int32@1']['input'] | null;
      readonly close: CodecTypes['mongo/string@1']['input'] | null;
      readonly open: CodecTypes['mongo/string@1']['input'] | null;
      readonly region: CodecTypes['mongo/string@1']['input'] | null;
      readonly recomended: CodecTypes['mongo/bool@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Education: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly logo: CodecTypes['mongo/string@1']['input'] | null;
      readonly web: CodecTypes['mongo/string@1']['input'] | null;
      readonly level: CodecTypes['mongo/string@1']['input'];
      readonly grade: CodecTypes['mongo/string@1']['input'] | null;
      readonly department: CodecTypes['mongo/string@1']['input'] | null;
      readonly studyProgram: CodecTypes['mongo/string@1']['input'] | null;
      readonly start: CodecTypes['mongo/date@1']['input'];
      readonly end: CodecTypes['mongo/date@1']['input'] | null;
      readonly place: CodecTypes['mongo/string@1']['input'];
      readonly academicScore: AcademicScoreInput | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Organization: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly orgName: CodecTypes['mongo/string@1']['input'];
      readonly desc: CodecTypes['mongo/string@1']['input'] | null;
      readonly period: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly Portfolio: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly slug: CodecTypes['mongo/string@1']['input'];
      readonly image: CodecTypes['mongo/string@1']['input'];
      readonly techstack: ReadonlyArray<CodecTypes['mongo/string@1']['input']>;
      readonly shortDesc: CodecTypes['mongo/string@1']['input'] | null;
      readonly desc: CodecTypes['mongo/string@1']['input'] | null;
      readonly demoLink: CodecTypes['mongo/string@1']['input'] | null;
      readonly sourceCode: CodecTypes['mongo/string@1']['input'] | null;
      readonly private: CodecTypes['mongo/bool@1']['input'];
      readonly categoryIds: ReadonlyArray<CodecTypes['mongo/objectId@1']['input']>;
      readonly careerIds: ReadonlyArray<CodecTypes['mongo/objectId@1']['input']>;
      readonly ratings: ReadonlyArray<PortfolioRatingInput>;
      readonly galleries: ReadonlyArray<PortfolioGalleryInput>;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly PortfolioCategory: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly color: CodecTypes['mongo/string@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly password: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
  };
};

export namespace Models {
  export type unbound_User = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    email: CodecTypes['mongo/string@1']['output'];
    password: CodecTypes['mongo/string@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_Education = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    logo: CodecTypes['mongo/string@1']['output'] | null;
    web: CodecTypes['mongo/string@1']['output'] | null;
    level: CodecTypes['mongo/string@1']['output'];
    grade: CodecTypes['mongo/string@1']['output'] | null;
    department: CodecTypes['mongo/string@1']['output'] | null;
    studyProgram: CodecTypes['mongo/string@1']['output'] | null;
    start: CodecTypes['mongo/date@1']['output'];
    end: CodecTypes['mongo/date@1']['output'] | null;
    place: CodecTypes['mongo/string@1']['output'];
    academicScore: AcademicScoreOutput | null;
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_Organization = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    orgName: CodecTypes['mongo/string@1']['output'];
    desc: CodecTypes['mongo/string@1']['output'] | null;
    period: CodecTypes['mongo/string@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_Career = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    position: CodecTypes['mongo/string@1']['output'];
    company: CodecTypes['mongo/string@1']['output'];
    location: CodecTypes['mongo/string@1']['output'];
    startDate: CodecTypes['mongo/date@1']['output'];
    endDate: CodecTypes['mongo/date@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_PortfolioCategory = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    color: CodecTypes['mongo/string@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_Award = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    event: CodecTypes['mongo/string@1']['output'];
    award: CodecTypes['mongo/string@1']['output'];
    icon: CodecTypes['mongo/string@1']['output'] | null;
    year: CodecTypes['mongo/int32@1']['output'];
    rank: CodecTypes['mongo/int32@1']['output'] | null;
    date: CodecTypes['mongo/date@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_Portfolio = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    slug: CodecTypes['mongo/string@1']['output'];
    image: CodecTypes['mongo/string@1']['output'];
    techstack: ReadonlyArray<CodecTypes['mongo/string@1']['output']>;
    shortDesc: CodecTypes['mongo/string@1']['output'] | null;
    desc: CodecTypes['mongo/string@1']['output'] | null;
    demoLink: CodecTypes['mongo/string@1']['output'] | null;
    sourceCode: CodecTypes['mongo/string@1']['output'] | null;
    private: CodecTypes['mongo/bool@1']['output'];
    categoryIds: ReadonlyArray<CodecTypes['mongo/objectId@1']['output']>;
    careerIds: ReadonlyArray<CodecTypes['mongo/objectId@1']['output']>;
    ratings: ReadonlyArray<PortfolioRatingOutput>;
    galleries: ReadonlyArray<PortfolioGalleryOutput>;
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type unbound_CoffeePlace = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    address: CodecTypes['mongo/string@1']['output'];
    description: CodecTypes['mongo/string@1']['output'] | null;
    mapCoordinate: CodecTypes['mongo/string@1']['output'] | null;
    mapUrl: CodecTypes['mongo/string@1']['output'] | null;
    image: CodecTypes['mongo/string@1']['output'] | null;
    wifiProvider: CodecTypes['mongo/string@1']['output'] | null;
    wifiSpeed: 'WEAK' | 'MEDIUM' | 'STRONG';
    price: 'CHEAP' | 'MEDIUM' | 'EXPENSIVE';
    parkFee: CodecTypes['mongo/int32@1']['output'] | null;
    close: CodecTypes['mongo/string@1']['output'] | null;
    open: CodecTypes['mongo/string@1']['output'] | null;
    region: CodecTypes['mongo/string@1']['output'] | null;
    recomended: CodecTypes['mongo/bool@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  __unbound__: {
    User: Models.unbound_User;
    Education: Models.unbound_Education;
    Organization: Models.unbound_Organization;
    Career: Models.unbound_Career;
    PortfolioCategory: Models.unbound_PortfolioCategory;
    Award: Models.unbound_Award;
    Portfolio: Models.unbound_Portfolio;
    CoffeePlace: Models.unbound_CoffeePlace;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly awards: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly event: { readonly bsonType: 'string' };
                    readonly award: { readonly bsonType: 'string' };
                    readonly icon: { readonly bsonType: readonly ['null', 'string'] };
                    readonly year: { readonly bsonType: 'int' };
                    readonly rank: { readonly bsonType: readonly ['null', 'int'] };
                    readonly date: { readonly bsonType: readonly ['null', 'date'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'award',
                    'createdAt',
                    'event',
                    'updatedAt',
                    'year',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly careers: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly position: { readonly bsonType: 'string' };
                    readonly company: { readonly bsonType: 'string' };
                    readonly location: { readonly bsonType: 'string' };
                    readonly startDate: { readonly bsonType: 'date' };
                    readonly endDate: { readonly bsonType: readonly ['null', 'date'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'company',
                    'createdAt',
                    'location',
                    'position',
                    'startDate',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly coffee_places: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly address: { readonly bsonType: 'string' };
                    readonly description: { readonly bsonType: readonly ['null', 'string'] };
                    readonly mapCoordinate: { readonly bsonType: readonly ['null', 'string'] };
                    readonly mapUrl: { readonly bsonType: readonly ['null', 'string'] };
                    readonly image: { readonly bsonType: readonly ['null', 'string'] };
                    readonly wifiProvider: { readonly bsonType: readonly ['null', 'string'] };
                    readonly wifiSpeed: {
                      readonly bsonType: 'string';
                      readonly enum: readonly ['WEAK', 'MEDIUM', 'STRONG'];
                    };
                    readonly price: {
                      readonly bsonType: 'string';
                      readonly enum: readonly ['CHEAP', 'MEDIUM', 'EXPENSIVE'];
                    };
                    readonly parkFee: { readonly bsonType: readonly ['null', 'int'] };
                    readonly close: { readonly bsonType: readonly ['null', 'string'] };
                    readonly open: { readonly bsonType: readonly ['null', 'string'] };
                    readonly region: { readonly bsonType: readonly ['null', 'string'] };
                    readonly recomended: { readonly bsonType: readonly ['null', 'bool'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'address',
                    'createdAt',
                    'name',
                    'price',
                    'updatedAt',
                    'wifiSpeed',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly educations: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly logo: { readonly bsonType: readonly ['null', 'string'] };
                    readonly web: { readonly bsonType: readonly ['null', 'string'] };
                    readonly level: { readonly bsonType: 'string' };
                    readonly grade: { readonly bsonType: readonly ['null', 'string'] };
                    readonly department: { readonly bsonType: readonly ['null', 'string'] };
                    readonly studyProgram: { readonly bsonType: readonly ['null', 'string'] };
                    readonly start: { readonly bsonType: 'date' };
                    readonly end: { readonly bsonType: readonly ['null', 'date'] };
                    readonly place: { readonly bsonType: 'string' };
                    readonly academicScore: {
                      readonly oneOf: readonly [
                        { readonly bsonType: 'null' },
                        {
                          readonly bsonType: 'object';
                          readonly properties: {
                            readonly type: { readonly bsonType: 'string' };
                            readonly label: { readonly bsonType: 'string' };
                            readonly value: { readonly bsonType: 'double' };
                            readonly scale: { readonly bsonType: 'double' };
                          };
                          readonly additionalProperties: false;
                          readonly required: readonly ['label', 'scale', 'type', 'value'];
                        },
                      ];
                    };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'level',
                    'name',
                    'place',
                    'start',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly organizations: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly orgName: { readonly bsonType: 'string' };
                    readonly desc: { readonly bsonType: readonly ['null', 'string'] };
                    readonly period: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'orgName',
                    'period',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly portfolio_categories: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly color: { readonly bsonType: readonly ['null', 'string'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'createdAt', 'name', 'updatedAt'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly portfolios: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'slug'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly slug: { readonly bsonType: 'string' };
                    readonly image: { readonly bsonType: 'string' };
                    readonly techstack: {
                      readonly bsonType: 'array';
                      readonly items: { readonly bsonType: 'string' };
                    };
                    readonly shortDesc: { readonly bsonType: readonly ['null', 'string'] };
                    readonly desc: { readonly bsonType: readonly ['null', 'string'] };
                    readonly demoLink: { readonly bsonType: readonly ['null', 'string'] };
                    readonly sourceCode: { readonly bsonType: readonly ['null', 'string'] };
                    readonly private: { readonly bsonType: 'bool' };
                    readonly categoryIds: {
                      readonly bsonType: 'array';
                      readonly items: { readonly bsonType: 'objectId' };
                    };
                    readonly careerIds: {
                      readonly bsonType: 'array';
                      readonly items: { readonly bsonType: 'objectId' };
                    };
                    readonly ratings: {
                      readonly bsonType: 'array';
                      readonly items: {
                        readonly bsonType: 'object';
                        readonly properties: {
                          readonly id: { readonly bsonType: 'string' };
                          readonly rating: { readonly bsonType: 'int' };
                          readonly comment: { readonly bsonType: readonly ['null', 'string'] };
                          readonly createdAt: { readonly bsonType: 'date' };
                        };
                        readonly additionalProperties: false;
                        readonly required: readonly ['createdAt', 'id', 'rating'];
                      };
                    };
                    readonly galleries: {
                      readonly bsonType: 'array';
                      readonly items: {
                        readonly bsonType: 'object';
                        readonly properties: {
                          readonly id: { readonly bsonType: 'string' };
                          readonly imageUrl: { readonly bsonType: 'string' };
                          readonly description: { readonly bsonType: readonly ['null', 'string'] };
                          readonly createdAt: { readonly bsonType: 'date' };
                        };
                        readonly additionalProperties: false;
                        readonly required: readonly ['createdAt', 'id', 'imageUrl'];
                      };
                    };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'careerIds',
                    'categoryIds',
                    'createdAt',
                    'galleries',
                    'image',
                    'name',
                    'private',
                    'ratings',
                    'slug',
                    'techstack',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly users: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly password: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'createdAt',
                    'email',
                    'name',
                    'password',
                    'updatedAt',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly users: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly educations: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Education';
    };
    readonly organizations: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Organization';
    };
    readonly careers: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Career' };
    readonly portfolio_categories: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'PortfolioCategory';
    };
    readonly awards: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Award' };
    readonly portfolios: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Portfolio';
    };
    readonly coffee_places: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'CoffeePlace';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly Award: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly event: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly award: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly icon: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly year: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly rank: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly date: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'awards' };
          };
          readonly Career: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly position: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly company: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly startDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly endDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'careers' };
          };
          readonly CoffeePlace: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly address: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly mapCoordinate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly mapUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly wifiProvider: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly wifiSpeed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly price: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly parkFee: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly close: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly open: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly region: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly recomended: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'coffee_places' };
          };
          readonly Education: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly logo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly web: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly level: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly grade: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly department: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly studyProgram: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly start: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly end: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly place: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly academicScore: {
                readonly nullable: true;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'AcademicScore' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'educations' };
          };
          readonly Organization: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly orgName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly desc: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly period: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'organizations' };
          };
          readonly Portfolio: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly slug: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly image: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly techstack: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
                readonly many: true;
              };
              readonly shortDesc: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly desc: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly demoLink: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly sourceCode: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly private: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly categoryIds: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
                readonly many: true;
              };
              readonly careerIds: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
                readonly many: true;
              };
              readonly ratings: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'PortfolioRating' };
                readonly many: true;
              };
              readonly galleries: {
                readonly nullable: false;
                readonly type: { readonly kind: 'valueObject'; readonly name: 'PortfolioGallery' };
                readonly many: true;
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'portfolios' };
          };
          readonly PortfolioCategory: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly color: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'portfolio_categories' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: { readonly collection: 'users' };
          };
        };
        readonly valueObjects: {
          readonly AcademicScore: {
            readonly fields: {
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
              readonly scale: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
              };
            };
          };
          readonly PortfolioRating: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly rating: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly comment: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
          };
          readonly PortfolioGallery: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly imageUrl: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
          };
        };
        readonly enum: {
          readonly WifiSpeed: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'WEAK'; readonly value: 'WEAK' },
              { readonly name: 'MEDIUM'; readonly value: 'MEDIUM' },
              { readonly name: 'STRONG'; readonly value: 'STRONG' },
            ];
          };
          readonly CafePrice: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'CHEAP'; readonly value: 'CHEAP' },
              { readonly name: 'MEDIUM'; readonly value: 'MEDIUM' },
              { readonly name: 'EXPENSIVE'; readonly value: 'EXPENSIVE' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};
  readonly valueObjects: {
    readonly AcademicScore: {
      readonly fields: {
        readonly type: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly label: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly value: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
        readonly scale: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/double@1' };
        };
      };
    };
    readonly PortfolioRating: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly rating: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
        };
        readonly comment: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
    };
    readonly PortfolioGallery: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly imageUrl: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly description: {
          readonly nullable: true;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
        };
      };
    };
  };
  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
